version: '3'

#####################################################################
# Services

services:

 ######################################    
 # Infraestructura

  rabbitmq-server:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
      - RABBITMQ_DEFAULT_VHOST=/
    ports:
      - 15672:15672
      - 5672:5672
    labels:
      name: "rabbit1"
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins"
    networks:
      service:
        aliases:
        - rabbitmq_serv    

#  gitlab-server:
#    image: "gitlab/gitlab-ce:latest"
#    restart: always
#    hostname: "gitlab1"
#    environment:
#      - GITLAB_OMNIBUS_CONFIG="external_url \"http://gitlab1:9090\"; gitlab_rails[\"gitlab_shell_ssh_port\"] = 2224"
#    ports:
#      - "9090:9090"
#      - "2224:22"
#    volumes:
#      - "/srv/gitlab/config:/etc/gitlab"
#      - "/srv/gitlab/logs:/var/log/gitlab"
##      - "./gitlab/data:/var/opt/gitlab" 
#      - "./gitlab-data:/var/opt/gitlab"       
#    networks:
#      service:
#        aliases:
#        - gitlab_serv
        
  gitlab-server:        
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "localhost"
    environment: 
      GITLAB_OMNIBUS_CONFIG: | 
        external_url "http://localhost"; 
    ports: 
      - "9090:9090"
      - "2224:22"
    volumes: 
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "gitlab-data:/var/opt/gitlab" 
    networks:
      service:
        aliases:
        - gitlab_serv                         

  config-server:
    build: ./tcp-microservices-git-config-server/target/docker
    environment:
      - SERVER_PORT=8888
      - PROFILE=native
      - TZ=Europe/Madrid
      - MANAGEMENT_PORT=8081      
      - RABBITMQ_HOST=rabbitmq_serv
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PWD=rabbitmq
      - EUREKA_URL=http://eureka-server:18761/eureka/
    volumes:
      - ./misc/config:/tmp
    ports:
      - 28888:8888
#    depends_on:
#      - rabbitmq-server
#      - eureka-server
    networks:
#      - service
      service:
        aliases:
        - config_serv

  custom-config-server:
    build: ./tcp-microservices-custom-config-server/target/docker
    environment:
      - SERVER_PORT=9999
      - TZ=Europe/Madrid
      - MANAGEMENT_PORT=8081      
      - RABBITMQ_HOST=rabbitmq_serv
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PWD=rabbitmq
      - EUREKA_URL=http://eureka-server:18761/eureka/
    volumes:
      - ./misc/config:/tmp
    ports:
      - 29999:9999
#    depends_on:
#      - rabbitmq-server
#      - eureka-server
    networks:
#      - service
      service:
        aliases:
        - custom-config_serv
        
  eureka-server:
    build: ./tcp-microservices-git-eureka-server/target/docker
    environment:
      - SERVER_PORT=18761
    ports:
      - 18761:18761
    networks:
#      - service
      service:
        aliases:
        - eureka_serv       
                         
  ######################################
  # Microservices

  config-client:      
    build: ./tcp-microservices-git-config-client/target/docker
    image: tcp-microservices-git-config-client-service
    environment:
      - SERVICE_NAME=config-service
      - SERVER_PORT=8100
      - PROFILE=dev
      - MANAGEMENT_PORT=8101
      - RABBITMQ_HOST=rabbitmq_serv
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PWD=rabbitmq   
      - EUREKA_URL=http://eureka-server:18761/eureka/
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 28100:8100
      - 28101:8101
#    depends_on:
#      - config-server
    networks:
      service:
        aliases:
          - config-client
          - "{{.ID}}"   

  simple-client:      
    build: ./tcp-microservices-git-simple-client/target/docker
    image: tcp-microservices-git-simple-client-service
    environment:
      - SERVICE_NAME=simple-service
      - SERVER_PORT=8200
      - MANAGEMENT_PORT=8201
      - RABBITMQ_HOST=rabbitmq_serv
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PWD=rabbitmq  
      - EUREKA_URL=http://eureka-server:18761/eureka/
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 28200:8200
      - 28201:8201
#    depends_on:
#      - config-server
    networks:
      service:
        aliases:
          - simple-client
          - "{{.ID}}"  
                              
#####################################################################
# Networks

networks:
  service:

#####################################################################
# Volumes
# Necesario para que funcione la imagen de GitLab con Hyper-V
# Se crean así: docker volume create --name=gitlab-data
  
volumes: 
  gitlab-data: 
    external: true