version: '3'

#####################################################################
# Services

services:

 ######################################    
 # Infraestructura

 ##Messaging, DB, Logs, Conf, etc. 

#  couchbase:
#    image: couchbase/server
#    ports:
#      - 8091:8091
#      - 8092:8092
#      - 8093:8093
#      - 8094:8094
#      - 11210:11210
#    networks:
#      service:
#        aliases:
#        - couchbase_serv   
                 
  ######################################
  # Microservices
  atomikos-coord-service:      
    build: ./tcp-microservices-atomikos-coord-service/target/docker
    image: tcp-microservices-atomikos-coord-service
    environment:
      - SERVICE_NAME=atomikos-coord-service
      - SERVER_PORT=8070
      - MANAGEMENT_PORT=8071
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
      - SERVICE1_URL=http://atomikos-service1:8080/tcp-microservices-atomikos-service1
      - SERVICE2_URL=http://atomikos-service2:8090/tcp-microservices-atomikos-service2
      - COORDINATOR_SERVER_URL=http://atomikos-coordinator-server:8888
    ports:
      - 28070:8070
      - 28071:8071
    depends_on:
      - atomikos-coordinator-server
      - atomikos-service1
      - atomikos-service2
    networks:
      service:
        aliases:
          - atomikos-coord-service
          - "{{.ID}}"
 
  atomikos-service1:      
    build: ./tcp-microservices-atomikos-service1/target/docker
    image: tcp-microservices-atomikos-service1
    environment:
      - SERVICE_NAME=atomikos-service1
      - SERVER_PORT=8080
      - PROFILE=dev
      - MANAGEMENT_PORT=8081
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 28080:8080
      - 28081:8081
    networks:
      service:
        aliases:
          - atomikos-service1
          - "{{.ID}}"
          
  atomikos-service2:      
    build: ./tcp-microservices-atomikos-service2/target/docker
    image: tcp-microservices-atomikos-service2
    environment:
      - SERVICE_NAME=atomikos-service2
      - SERVER_PORT=8090
      - PROFILE=dev
      - MANAGEMENT_PORT=8091
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 28090:8090
      - 28091:8091
    networks:
      service:
        aliases:
          - atomikos-service2
          - "{{.ID}}"          

  atomikos-coordinator-server:      
    build: ./tcp-microservices-atomikos-coordinator-server/target/docker
    image: tcp-microservices-atomikos-coordinator-server
    environment:
      - SERVICE_NAME=atomikos-coordinator-server
      - SERVER_PORT=8888
      - PROFILE=dev
      - MANAGEMENT_PORT=9999
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 28888:8888
      - 28999:9999
    networks:
      service:
        aliases:
          - atomikos-coordinator-server
          - "{{.ID}}"  
          
#####################################################################
# Networks

networks:
  service:
