server:
  context-path: /${project.artifactId}
  port: ${SERVER_PORT}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json

endpoints:
    metrics:
        sensitive: false
        
management:
  context-path: /admin
  port: ${MANAGEMENT_PORT}
  address: ${MANAGEMENT_ADDRESS:0.0.0.0}
  info.git:
    enabled: true
    mode: full
  
spring:
  application:
    name: ${project.artifactId}
  pid:
    file: ${project.artifactId}.pid
  http:
    encoding:
      enabled: true
      charset: UTF-8

app:
  service1:
    url: ${SERVICE1_URL}
  service2:
    url: ${SERVICE2_URL}
  coord:
    server:
      url: ${COORDINATOR_SERVER_URL}
    
logging:
  level:
    tcp.microservices: DEBUG
    root: INFO