server:
  context-path: /${project.artifactId}
  port: ${SERVER_PORT}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json

endpoints:
    metrics:
        sensitive: false
    refresh:
        sensitive: false
        enabled: true
    env:
        sensitive: false
        enabled: true
    info:
        sensitive: false
        enabled: true
                
management:
  context-path: /admin
  port: ${MANAGEMENT_PORT}
  address: ${MANAGEMENT_ADDRESS:0.0.0.0}
  info.git:
    enabled: true
    mode: full
  security: 
    enabled: false

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PWD}
 
app:
  version: "@project.version@"

logging:
  level:
    tcp.microservices: DEBUG
    root: INFO

  
