server:
  context-path: /${project.artifactId}
  port: ${SERVER_PORT}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json
    
spring:
  application:
    name: ${project.artifactId}
  pid:
    file: ${project.artifactId}.pid
  http:
    encoding:
      enabled: true
      charset: UTF-8
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
      
app:
  version: "@project.version@"
  sorter: mergersoft
  storage: memory

logging:
  level:
    ust.laboratory: DEBUG
    root: INFO

  
