version: '3.3'

#####################################################################
# Services

services:

 ######################################    
 # Infraestructura

 ##Messaging, DB, Logs, Conf, etc. 

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment: 
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
    volumes:
      # Data persistency
      - influxdb:/var/lib/influxd
    networks:       
      service:         
        aliases:           
          - lab-influxb
          
# Es un colector de datos que lo vuelca en influx
#  telegraf:
#    image: telegraf:latest
#    container_name: telegraf
#    links:
#      - influxdb
#    volumes:
#      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource      
    depends_on:
      - influxdb
    volumes:
      # Data persistency
      - grafana:/var/lib/grafana
                    
  ######################################
  # Microservices 
  metrics-service:      
    build: ./target/docker
    image: metrics-service
    container_name: metrics-service
    environment:
      - SERVICE_NAME=metrics-service
      - SERVER_PORT=8080
      - INFLUXDB_URL=http://lab-influxb:8086
      - INFLUXDB_DATABASE=My_Database
      - JAVA_OPTS=-server -Xms512M -Xmx1024M -Xmn256m -Xss2m -Dfile.encoding=UTF-8
      - TZ=Europe/Madrid
    ports:
      - 18080:8080
    depends_on:
      - influxdb
    networks:
      service:
        aliases:
          - metrics-service
          - "{{.ID}}"

#####################################################################
# Volumes

volumes:
  grafana:
  influxdb:

#####################################################################
# Networks

networks:
  service:
    