FROM debian:jessie

ENV JAVA_HOME /opt/java
ENV PATH /opt/flume/bin:/opt/java/bin:$PATH
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qq \ 
    && apt-get install -q -y --no-install-recommends wget \
    && mkdir /opt/java \ 
    && wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u171-b11/512cd62ec5174c3487ac17c61aaa89e8/jre-8u171-linux-x64.tar.gz \
          | tar zxvf - -C /opt/java --strip 1 \
    && mkdir /opt/flume \ 
    && wget -qO- http://archive.apache.org/dist/flume/1.8.0/apache-flume-1.8.0-bin.tar.gz \
          | tar zxvf - -C /opt/flume --strip 1


ADD ./additional_jars/kafka_2.10-0.10.2.1/libs /opt/flume/lib
ADD ./additional_jars/flume-ingestion/stratio-sinks/stratio-jdbc-sink/target/stratio-jdbc-sink-0.8.0-SNAPSHOT.jar /opt/flume/lib
ADD ./additional_jars\mysql-connector-java-5.1.46\mysql-connector-java-5.1.46-bin.jar /opt/flume/lib
ADD ./additional_jars/jOOQ-3.10.6/jOOQ-lib/jooq-3.10.6.jar /opt/flume/lib

ADD start-flume.sh /opt/flume/bin/start-flume

ENTRYPOINT [ "start-flume" ]