server:
  context-path: /${project.artifactId}
  port: 11111 #${SERVER_PORT}
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json

endpoints:
    metrics:
        sensitive: false
    refresh:
        sensitive: false
        enabled: true
    env:
        sensitive: false
        enabled: true
                
management:
  context-path: /admin
  port: 22222 #${MANAGEMENT_PORT}
  address: 0.0.0.0 #${MANAGEMENT_ADDRESS:0.0.0.0}
  info.git:
    enabled: true
    mode: full
  
spring:
  application:
    name: ${project.artifactId}
  pid:
    file: ${project.artifactId}.pid
  http:
    encoding:
      enabled: true
      charset: UTF-8
      
app:
  version: "@project.version@"

logging:
  level:
    tcp.microservices: DEBUG
    root: INFO

  
