server:
  context-path: /${project.artifactId}
  port: 18008
  compression:
    enabled: true
    mime-types:
    - application/xml
    - application/json
    
spring:
  application:
    name: ${project.artifactId}
  pid:
    file: ${project.artifactId}.pid
  http:
    encoding:
      enabled: true
      charset: UTF-8
      
app:
  version: "@project.version@"
  service2_name: srv1-srv2
  service2_url: http://srv1-srv2:9090

logging:
  level:
    ust.laboratory: DEBUG
    root: INFO

  
