apiVersion: v1
kind: Pod
metadata:
  name: service1
  labels:
   app: service1
spec:
  containers:
  - image: fernison/service1
    name: service1-container
    ports:
    - name: service1-port
      containerPort: 18008 
